// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		AppMain: typeof import('./layout/components/AppMain.vue')['default']
		Breadcrumb: typeof import('./components/Breadcrumb/index.vue')['default']
		ContextMenu: typeof import('./components/TagView/ContextMenu.vue')['default']
		ElAvatar: typeof import('element-plus/es')['ElAvatar']
		ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
		ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
		ElButton: typeof import('element-plus/es')['ElButton']
		ElCard: typeof import('element-plus/es')['ElCard']
		ElCol: typeof import('element-plus/es')['ElCol']
		ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
		ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
		ElDialog: typeof import('element-plus/es')['ElDialog']
		ElDrawer: typeof import('element-plus/es')['ElDrawer']
		ElDropdown: typeof import('element-plus/es')['ElDropdown']
		ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
		ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
		ElForm: typeof import('element-plus/es')['ElForm']
		ElFormItem: typeof import('element-plus/es')['ElFormItem']
		ElInput: typeof import('element-plus/es')['ElInput']
		ElMenu: typeof import('element-plus/es')['ElMenu']
		ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
		ElOption: typeof import('element-plus/es')['ElOption']
		ElPagination: typeof import('element-plus/es')['ElPagination']
		ElRow: typeof import('element-plus/es')['ElRow']
		ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
		ElSelect: typeof import('element-plus/es')['ElSelect']
		ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
		ElTable: typeof import('element-plus/es')['ElTable']
		ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
		ElTabPane: typeof import('element-plus/es')['ElTabPane']
		ElTabs: typeof import('element-plus/es')['ElTabs']
		ElTooltip: typeof import('element-plus/es')['ElTooltip']
		ElTreeV2: typeof import('element-plus/es')['ElTreeV2']
		Hamburger: typeof import('./components/Hamburger/index.vue')['default']
		HeaderSearch: typeof import('./components/HeaderSearch/index.vue')['default']
		MenuItem: typeof import('./layout/components/SideBar/MenuItem.vue')['default']
		NavBar: typeof import('./layout/components/NavBar.vue')['default']
		PanThumb: typeof import('./components/PanThumb/index.vue')['default']
		RouterLink: typeof import('vue-router')['RouterLink']
		RouterView: typeof import('vue-router')['RouterView']
		Screenfull: typeof import('./components/Screenfull/index.vue')['default']
		SelectColor: typeof import('./components/ThemeSelect/SelectColor/index.vue')['default']
		SideBar: typeof import('./layout/components/SideBar/index.vue')['default']
		SidebarItem: typeof import('./layout/components/SideBar/SidebarItem.vue')['default']
		SidebarMenu: typeof import('./layout/components/SideBar/SidebarMenu.vue')['default']
		SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
		TagView: typeof import('./components/TagView/index.vue')['default']
		ThemeSelect: typeof import('./components/ThemeSelect/index.vue')['default']
	}
}

export {}
